version: '3'
services:
  webrun:
    image: 'makerskin/webrun-bootstrap:latest'
    restart: always
    ports:
      - 8080:8080
    volumes:
      - /home/docker/compose/webrun:/usr/local/tomcat/webrun
  webrunutf8:
    image: 'makerskin/webrun-bootstrap-utf8:latest'
    restart: always
    ports:
      - 8080:8080
    volumes:
      - /home/docker/compose/webrun:/usr/local/tomcat/webrun
